-- Simple FPS controller: WASD to move, Space to jump.
--
-- Regenerated by hand - the AI Forge originally produced a broken, single-
-- line version of this file (an editor bug where the AI's response was
-- over-escaped in transit, and the script never returned a table). Both
-- issues are now fixed at the source. See fps_controller.lua for a fuller
-- example with sprint and camera switching.

local FPSController = {}

function FPSController:on_start()
    self.walk_speed = 4.5
    self.jump_speed = 6.0
    self.gravity = -18.0
    self.velocity_y = 0.0
    self.grounded = true
    self.camera:setMode("fps")
    -- Cursor lock moved off the per-entity Inspector checkbox onto
    -- whatever actually drives the player. Without this registration
    -- wantsCursorLock stays false and the mouse is never captured.
    self.gameManager:setCursorLock(true)
    self.managers:register("FPSController")
end

function FPSController:on_update(delta_time)
    -- Same WASD / getRight contract as fps_controller.lua — do not swap A/D.
    local forward_axis = self.input:getAxis("W", "S")
    local strafe_axis = self.input:getAxis("D", "A")

    local forward = self.entity:getForward()
    local right = self.entity:getRight()
    local move_x = forward.x * forward_axis + right.x * strafe_axis
    local move_z = forward.z * forward_axis + right.z * strafe_axis
    local length = math.sqrt(move_x * move_x + move_z * move_z)
    if length > 0.0001 then
        move_x = move_x / length
        move_z = move_z / length
    end

    if self.grounded and self.input:isKeyPressed("Space") then
        self.velocity_y = self.jump_speed
        self.grounded = false
    end
    self.velocity_y = self.velocity_y + self.gravity * delta_time

    local position = self.entity:getPosition()
    position.x = position.x + move_x * self.walk_speed * delta_time
    position.z = position.z + move_z * self.walk_speed * delta_time
    position.y = position.y + self.velocity_y * delta_time

    if position.y <= 0.0 then
        position.y = 0.0
        self.velocity_y = 0.0
        self.grounded = true
    end

    self.entity:setPosition(position)
end


-- Releasing the registration tells the engine nothing is driving the
-- player any more, so the cursor is not left captured.
function FPSController:on_end()
    self.managers:unregister("FPSController")
    self.gameManager:setCursorLock(false)
end

return FPSController
